import { build } from "esbuild";
import { cp, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(root, "site/assets/mermaid");
await mkdir(output, { recursive: true });
const result = await build({
  absWorkingDir: root,
  entryPoints: ["src/mermaid-renderer.js"],
  outfile: "site/assets/mermaid/renderer.js",
  bundle: true,
  format: "iife",
  platform: "browser",
  // Lower syntax beyond Mermaid 12's published ES2024 bundle. Runtime APIs such
  // as Array.at still require Chrome 100 / Safari 15.4-class browsers; no claim
  // that syntax lowering alone supplies missing platform methods.
  target: ["chrome100", "safari15.4"],
  minify: true,
  legalComments: "linked",
  metafile: true,
  logLevel: "info",
});

// Copy the license notices of every package whose code entered the bundle.
// This supplements legal comments preserved by esbuild, including packages
// whose distributed source did not repeat their package-level license text.
const packageRoots = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const parts = input.split("/");
  const marker = parts.lastIndexOf("node_modules");
  if (marker < 0) continue;
  const end = marker + (parts[marker + 1].startsWith("@") ? 3 : 2);
  packageRoots.add(parts.slice(0, end).join("/"));
}
const notices = ["Generated by npm run build:mermaid. Do not edit by hand.\n"];
for (const packageRoot of [...packageRoots].sort()) {
  const directory = path.join(root, packageRoot);
  const pkg = JSON.parse(await readFile(path.join(directory, "package.json"), "utf8"));
  notices.push(`\n===== ${pkg.name} ${pkg.version} (${pkg.license || "see notice"}) =====\n`);
  const licenses = (await readdir(directory)).filter(name => /^(licen[sc]e|copying|notice)([.-]|$)/i.test(name)).sort();
  if (!licenses.length) notices.push(`Package license declaration: ${JSON.stringify(pkg.license || pkg.licenses || "not specified")}\n`);
  for (const file of licenses) notices.push(await readFile(path.join(directory, file), "utf8"));
}
await writeFile(path.join(output, "THIRD_PARTY_NOTICES.txt"), notices.join("\n"));

// Optional mirror for local file:// learning packages, using the same relative URL.
// The destination is supplied explicitly, never inferred from HOME or the repo.
if (process.argv[2]) {
  const mirror = path.resolve(process.argv[2]);
  await mkdir(mirror, { recursive: true });
  for (const file of await readdir(output)) await cp(path.join(output, file), path.join(mirror, file));
}
